version: '3'
services:
  tomcat:
    image: tomcat:latest
    volumes:
      - .:/usr/local/tomcat/webapps
    ports:
      - 8888:8080
  jenkins:
    image: jenkins/jenkins:latest
    volumes:
      - D:/jenkins_home/:/var/jenkins_home jenkins/jenkins
    ports:
      - 8081:8080
      - 50000:50000