version: '3'
services:
  tomcat:
    image: tomcat:latest
    volumes:
      - D:/demo/webapps:/usr/local/tomcat/webapps
    ports:
      - 8082:8080
  jenkins:
    image: jenkins/jenkins
    volumes:
      - D:/jenkins_home:/var/jenkins_home
      - D:/demo/webapps:/home/webapps
    ports:
      - 8081:8080
      - 50000:50000